[build]
  publish = "."
  command = "pip install -r requirements.txt && pip install netlify-py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "none"
